The torch.nn module in PyTorch is a core library that provides a wide array of classes and functions designed to help developers build neural networks efficiently and effectively. It abstracts the complexity of creating and training neural networks by offering pre-built layers, loss functions, activation functions, and other utilities, enabling you to focus on designing and experimenting with model architectures. 

In [8]:
# Create Model Class
import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):

        out = self.linear(features) #Calculating z
        out = self.sigmoid(out) # Calculating Out

        return out

In [9]:
# Create Dataset
features = torch.rand(10, 5)

# Create Model
model = Model(features.shape[1])

# Call model for forward pass
# model.forward_pass(features)

model(features)

tensor([[0.4081],
        [0.4133],
        [0.3932],
        [0.3583],
        [0.3890],
        [0.4107],
        [0.3852],
        [0.3460],
        [0.3487],
        [0.4333]], grad_fn=<SigmoidBackward0>)

In [10]:
# Show model weight

model.linear.weight

Parameter containing:
tensor([[-0.0136, -0.0852, -0.2667, -0.2613, -0.2535]], requires_grad=True)

In [11]:
# Show model bias

model.linear.bias

Parameter containing:
tensor([-0.0081], requires_grad=True)

In [12]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [13]:
class Model2(nn.Module):

    def __init__(self, num_features):

        super().__init__()

        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):

        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out

In [14]:
features = torch.rand(10, 5)

In [19]:
model2 = Model2(features.shape[1])

model2(features)

tensor([[0.3710],
        [0.3793],
        [0.3649],
        [0.3773],
        [0.3756],
        [0.3816],
        [0.3578],
        [0.3722],
        [0.3824],
        [0.3745]], grad_fn=<SigmoidBackward0>)

In [20]:
summary(model2, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
class Model3(nn.Module):

    def __init__(self, num_features):

        super().__init__()

        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )

    def forward(self, features):

        out = self.network(features)

        return out

In [23]:
features = torch.rand(10, 5)
model3 = Model3(features.shape[1])

In [24]:
model3(features)

tensor([[0.6127],
        [0.6258],
        [0.6031],
        [0.6254],
        [0.6183],
        [0.6078],
        [0.6237],
        [0.6040],
        [0.6175],
        [0.6299]], grad_fn=<SigmoidBackward0>)

In [25]:
summary(model3, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model3                                   [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00