CODE FLOW:

1. Load the dataset
2. Basic Preprocessing
3. Training Pipeline
    a. Create a model
    b. Forward Pass
    c. Loss Calculation
    d. Backdrop
    e. Parameter Update
4. Model Evaluation

In [14]:
import pandas as pd

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [16]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-cancer-Detection/refs/heads/master/data.csv")
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [17]:
df.drop(columns=["id", "Unnamed: 32"], inplace=True)

In [18]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [19]:
X_train, X_test, Y_train, Y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [20]:
X_test.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
392       15.490         19.97          102.40      744.7          0.11600   
302       20.090         23.86          134.70     1247.0          0.10800   
176        9.904         18.06           64.60      302.4          0.09699   
530       11.750         17.56           75.89      422.9          0.10730   
427       10.800         21.98           68.79      359.9          0.08801   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
392           0.15620         0.18910              0.09113         0.1929   
302           0.18380         0.22830              0.12800         0.2249   
176           0.12940         0.13070              0.03716         0.1669   
530           0.09713         0.05282              0.04440         0.1598   
427           0.05743         0.03614              0.01404         0.2016   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
392                 0.06744  ...         21.20          29.41   
302                 0.07469  ...         23.68          29.43   
176                 0.08116  ...         11.26          24.39   
530                 0.06677  ...         13.50          27.98   
427                 0.05977  ...         12.76          32.04   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
392           142.10      1359.0            0.1681             0.3913   
302           158.80      1696.0            0.1347             0.3391   
176            73.07       390.2            0.1301             0.2950   
530            88.52       552.3            0.1349             0.1854   
427            83.69       489.5            0.1303             0.1696   

     concavity_worst  concave points_worst  symmetry_worst  \
392           0.5553               0.21210          0.3187   
302           0.4932               0.19230          0.3294   
176           0.3486               0.09910          0.2614   
530           0.1366               0.10100          0.2478   
427           0.1927               0.07485          0.2965   

     fractal_dimension_worst  
392                  0.10190  
302                  0.09469  
176                  0.11620  
530                  0.07757  
427                  0.07662  

[5 rows x 30 columns]

SCALING

In [21]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [22]:
X_train

array([[-0.09474187,  1.06845203, -0.12994246, ..., -0.80160804,
        -0.36994902, -1.1034738 ],
       [-0.77700252, -0.16552342, -0.77653879, ..., -0.43480868,
         0.25051411, -0.85616667],
       [-0.05227751, -0.01486363, -0.12215708, ..., -0.49383386,
        -0.849753  , -0.41722328],
       ...,
       [ 1.93505434,  1.38412017,  2.10159343, ...,  2.1065869 ,
         0.04577691,  0.79790049],
       [-0.43728767, -0.29466039, -0.50364072, ..., -1.47482641,
        -1.04198717, -1.53171125],
       [-0.36368279, -0.44053733, -0.35489898, ..., -0.47184999,
        -1.42489263, -0.71163653]], shape=(455, 30))

In [23]:
Y_train

243    B
515    B
481    B
540    B
418    B
      ..
112    B
234    B
563    M
360    B
397    B
Name: diagnosis, Length: 455, dtype: object

LABEL ENCODING

In [24]:
encoder = LabelEncoder()
Y_train = encoder.fit_transform(Y_train)
Y_test = encoder.fit_transform(Y_test)

In [25]:
Y_test

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0])

In [26]:
Y_train

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,

Numpy arrays to Pytorch tenors

In [27]:
import torch

In [37]:
X_train_tensor = torch.from_numpy(X_train).float()
Y_train_tensor = torch.from_numpy(Y_train).float()
Y_test_tensor = torch.from_numpy(Y_test).float()
X_test_tensor = torch.from_numpy(X_test).float()

Defining the model

In [38]:
import torch.nn as nn

class MySimpleNN(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    # def __init__(self, X):
    #     self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    #     self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)

        return out

    # def forward(self, X):
    #     z = torch.matmul(X, self.weights) + self.bias
    #     y_pred = torch.sigmoid(z)
    #     return y_pred
    
    # def loss_function(self, y_pred, y):
    #     # clamp prediction to avoid log(0)
    #     epsilion = 1e-7
    #     y_pred = torch.clamp(y_pred, epsilion, 1 - epsilion)

        # Calculate loss
        # loss = -(Y_train_tensor * torch.log(y_pred) + (1 - Y_train_tensor) * torch.log(1 - y_pred)).mean()
        # return loss

Important Parameters

In [39]:
learning_rate = 0.1
epochs = 25

In [40]:
# Loss Function
loss_function = nn.BCELoss()

Training Pipeline

In [42]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)


# Define loop
for epochs in range(epochs):

    # Forward Pass
    y_pred = model(X_train_tensor)
    
    # Loss Calculation
    loss = loss_function(y_pred, Y_train_tensor.view(-1, 1))

    # Zero gradients
    optimizer.zero_grad()

    
    # Backward Bias
    loss.backward()

    # parameter update
    optimizer.step()
    

    # Print loss in each epoch
    
    print(f'Epoch: {epochs + 1}, Loss: {loss.item()}')

    

In [ ]:
model.bias

tensor([-0.2131], dtype=torch.float64, requires_grad=True)

Evaluating Model

In [43]:
with torch.no_grad():
    y_pred = model(X_test_tensor)
    y_pred = (y_pred >= 0.5).float()
    accuracy = (y_pred.view(-1) == Y_test_tensor.view(-1)).sum().item() / Y_test_tensor.size(0)

print(f"Test Accuracy: {accuracy*100:.2f}%")


Test Accuracy: 73.68%
