CODE FLOW:

1. Load the dataset
2. Basic Preprocessing
3. Training Pipeline
    a. Create a model
    b. Forward Pass
    c. Loss Calculation
    d. Backdrop
    e. Parameter Update
4. Model Evaluation

In [2]:
import pandas as pd

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-cancer-Detection/refs/heads/master/data.csv")
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [5]:
df.drop(columns=["id", "Unnamed: 32"], inplace=True)

In [6]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [9]:
X_test.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
19        13.540         14.36           87.46      566.3          0.09779   
494       13.160         20.54           84.06      538.7          0.07335   
98        11.600         12.84           74.34      412.6          0.08983   
358        8.878         15.49           56.74      241.0          0.08293   
227       15.000         15.51           97.45      684.5          0.08371   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
19            0.08129         0.06664              0.04781         0.1885   
494           0.05275         0.01800              0.01256         0.1713   
98            0.07525         0.04196              0.03350         0.1620   
358           0.07698         0.04721              0.02381         0.1930   
227           0.10960         0.06505              0.03780         0.1881   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
19                  0.05766  ...        15.110          19.26   
494                 0.05888  ...        14.500          28.46   
98                  0.06582  ...        13.060          17.16   
358                 0.06621  ...         9.981          17.70   
227                 0.05907  ...        16.410          19.31   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
19             99.70       711.2            0.1440             0.1773   
494            95.29       648.3            0.1118             0.1646   
98             82.96       512.5            0.1431             0.1851   
358            65.27       302.0            0.1015             0.1248   
227           114.20       808.2            0.1136             0.3627   

     concavity_worst  concave points_worst  symmetry_worst  \
19           0.23900               0.12880          0.2977   
494          0.07698               0.04195          0.2687   
98           0.19220               0.08449          0.2772   
358          0.09441               0.04762          0.2434   
227          0.34020               0.13790          0.2954   

     fractal_dimension_worst  
19                   0.07259  
494                  0.07429  
98                   0.08756  
358                  0.07431  
227                  0.08362  

[5 rows x 30 columns]

SCALING

In [78]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [79]:
X_train

array([[ 0.24427854, -0.04626279,  0.2139842 , ...,  0.53121486,
         0.10324395,  0.02953704],
       [-0.25350064, -0.43200604, -0.31413136, ..., -0.96761869,
        -0.20913906, -0.66426862],
       [-1.42950395, -0.09245959, -1.29912831, ...,  0.01145806,
         0.38038375,  1.1611918 ],
       ...,
       [-1.08501813, -1.6354326 , -1.0665937 , ..., -0.70683374,
         0.06319485, -0.37890428],
       [-0.46562245, -0.83160834, -0.3779965 , ...,  0.91196693,
         1.74205327,  2.19046394],
       [-0.09794464,  1.03243241, -0.13358953, ..., -0.79597808,
        -0.37574333, -1.14187268]], shape=(455, 30))

In [80]:
Y_train

291    B
246    B
318    B
226    B
491    B
      ..
92     B
136    B
390    B
5      M
243    B
Name: diagnosis, Length: 455, dtype: object

LABEL ENCODING

In [81]:
encoder = LabelEncoder()
Y_train = encoder.fit_transform(Y_train)
Y_test = encoder.fit_transform(Y_test)

In [82]:
Y_test

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1])

In [83]:
Y_train

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,

Numpy arrays to Pytorch tenors

In [84]:
import torch

In [85]:
X_train_tensor = torch.from_numpy(X_train)
Y_train_tensor = torch.from_numpy(Y_train)
Y_test_tensor = torch.from_numpy(Y_test)
X_test_tensor = torch.from_numpy(X_test)

Defining the model

In [86]:
class MySimpleNN():
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        # clamp prediction to avoid log(0)
        epsilion = 1e-7
        y_pred = torch.clamp(y_pred, epsilion, 1 - epsilion)

        # Calculate loss
        loss = -(Y_train_tensor * torch.log(y_pred) + (1 - Y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

Important Parameters

In [87]:
learning_rate = 0.1
epochs = 25

Training Pipeline

In [88]:
# create model
model = MySimpleNN(X_train_tensor)
model.weights

# Define loop
for epochs in range(epochs):

    # Forward Pass
    y_pred = model.forward(X_train_tensor)
    
    # Loss Calculation
    loss = model.loss_function(y_pred, Y_train_tensor)

    # Backward Bias
    loss.backward()

    # parameter update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad
    
    # Zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # Print loss in each epoch
    
    print(f'Epoch: {epochs + 1}, Loss: {loss.item()}')

    

Epoch: 1, Loss: 2.7755975766793965
Epoch: 2, Loss: 2.6219402423546936
Epoch: 3, Loss: 2.4615230242026276
Epoch: 4, Loss: 2.3002362077012504
Epoch: 5, Loss: 2.1390052366536016
Epoch: 6, Loss: 1.9827485435897243
Epoch: 7, Loss: 1.8294142232791972
Epoch: 8, Loss: 1.6792303199263539
Epoch: 9, Loss: 1.5388018916656774
Epoch: 10, Loss: 1.4051215818999439
Epoch: 11, Loss: 1.2833834835347253
Epoch: 12, Loss: 1.1770903513240667
Epoch: 13, Loss: 1.0872448576300269
Epoch: 14, Loss: 1.0141362366676563
Epoch: 15, Loss: 0.9568834424391253
Epoch: 16, Loss: 0.913334383745984
Epoch: 17, Loss: 0.880599128535541
Epoch: 18, Loss: 0.8558243822633745
Epoch: 19, Loss: 0.8366690566072555
Epoch: 20, Loss: 0.821404817870687
Epoch: 21, Loss: 0.8088295200833491
Epoch: 22, Loss: 0.7981368674106495
Epoch: 23, Loss: 0.788798536724104
Epoch: 24, Loss: 0.7804725878705662
Epoch: 25, Loss: 0.7729376985496716


In [89]:
model.bias

tensor([-0.2131], dtype=torch.float64, requires_grad=True)

Evaluating Model

In [91]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()

print(Y_train_tensor)

tensor([0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
        1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
        1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
        0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
        0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
        1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
        0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,