Importing TORCH

In [2]:
import torch
print(torch.__version__)

c:\Users\FMC GROUP\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\_subclasses\functional_tensor.py:279: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\utils\tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


2.8.0+cpu


CHECK GPU

In [3]:
if torch.cuda.is_available():
    print("GPU IS AVAILABLE")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU IS NOT AVAILABLE")

GPU IS NOT AVAILABLE


Creating a Tensor

In [ ]:
# using empty

a = torch.empty(2,3)

In [9]:
# check type

type(a)

torch.Tensor

In [ ]:
# using zeroes

torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
# using ones

torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand

torch.rand(2,3)

tensor([[0.9273, 0.9143, 0.2635],
        [0.8469, 0.9254, 0.5956]])

In [14]:
# use of seed

torch.manual_seed(100)

torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [15]:
# manual seed

torch.manual_seed(100)

torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [16]:
# using tensor

torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
# other ways

# arange
print("using arange -> ", torch.arange(0,10,2))

# using linspace
print("using linspace -> ", torch.linspace(0,10,10))

# using eye
print("using eye -> ", torch.eye(5))

# using full 
print("using full -> ", torch.full((3,3), 5))



using arange ->  tensor([0, 2, 4, 6, 8])
using linspace ->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye ->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full ->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensor Shapes

In [18]:
x = torch.tensor([[1,2,3], [4,5,6]])

In [19]:
x.shape

torch.Size([2, 3])

In [20]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [24]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [32]:
torch.rand_like(x, dtype=torch.float64)

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

Tensor DataTypes

In [26]:
# find data type

x.dtype

torch.int64

In [28]:
# assign data type

torch.tensor([1.0,2.4,3.7], dtype=torch.int64)

tensor([1, 2, 3])

In [29]:
torch.tensor([1.0,2.4,3.7], dtype=torch.float64)

tensor([1.0000, 2.4000, 3.7000], dtype=torch.float64)

In [31]:
# using to()

x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

Mathematical Operation

1. Scalar Operation

In [33]:
x= torch.rand(2,2)

In [36]:
#addition
x+2

#subtraction
x - 2

#multiplication
x * 2

#division
x / 3

#int division
(x*100) // 3

#mod
((x*100) // 3)%2

#power
x ** 2

tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])

In [37]:
c = torch.tensor([1,2,-3,-4])

In [38]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [39]:
torch.neg(c)

tensor([-1, -2,  3,  4])

In [41]:
d = torch.tensor([1,2.6,3.5,4.3])
torch.round(d)

tensor([1., 3., 4., 4.])

In [42]:
torch.ceil(d)

tensor([1., 3., 4., 5.])

In [43]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [45]:
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.6000, 3.0000, 3.0000])